# Site settings 配置站点
title: 'Osu!Skins'
description: 'Osu!各种皮肤收集地，有喜欢的皮肤可以联系我哦'
keyword: 'osu!,皮肤,图包'
url: '' # your host

# if you don't need baseurl, you should leave this value blank.
baseurl: ''

# app

app:
  dl: 'https://github.com/soloopooo/osuskins/releases/download/1.0.0.22/osuskin_1.0.0.22.apk'
  dlx5: 'https://github.com/soloopooo/osuskins/releases/download/1.0.0.22/osuskin-corex5_1.0.0.22.apk'
  new: '1.0.0.21'
  time: '2019年11月06日'
  whatsnew: '1.修复android8以上闪退问题。</br>2.界面大改版，体验升级！</br>3.添加了收藏夹功能。</br>4.还有更多功能等你发现！</br></br>
Tips：可自行选择原生内核版或腾讯x5内核版。</br>提示：腾讯x5内核版相对于原生版启动速度较慢且无法体验到dplayer的快感，并且没有原生的长按菜单。但是腾讯x5内核版更稳定一些。'
  size: '原生：1,299KB</br>x5：1,289KB'

# tongji
my:
  numall: '183'
# Navigation links
nav:
  公告: '/forall'
  home: '/'
  tags: '/tags'
  osu!: '//osu.ppy.sh'

# Footer
footer:
  since: 2019

# Author 配置博主信息
author: 'soloopooo'
nickname: ''
bio: '一个osu手残玩家'
avatar: 'https://a.ppy.sh/9502298?1536448758.jpeg'

# Search
search: true

# Night mode
nightMode: true

# Comments 评论功能
comments: true

comments:
  disqus: true
  gitalk: true
  disqus_url: ''
  gitalk_clientID: '37e2ab700acf0e1a7490'
  gitalk_Secret: '19d5e73ca2861c1d59120faec084354af79ce73b'
  gitalk_repo: 'osuskins'
  gitalk_owner: 'soloopooo'
  gitalk_admin: 'soloopooo'
  distractionFreeMode: false

# MathJax 公式支持 by Ray-Eldath
mathjax: true

# Share
social-share: true
social-share-items: ['wechat', 'weibo', 'douban', 'twitter', 'QQ', 'Facebook']

# theme color 主题皮肤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings 配置社交网站
# url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  weibo: '//weibo.com/soloopooo'
  
  github: '//github.com/soloopooo'
  
  email: 'mailto:soloopooo@foxmail.com'

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 50
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md',]



# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# RSS
RSS: true

# Permalink
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:year/:month/:day/:title.html

# Plugins
plugins: [jekyll-paginate]
